apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: default  # Add the namespace field here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ismail039/api-gateway-project:tagname  # Replace with your image name and tag
          ports:
            - containerPort: 8083
