apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-recovery-service
  labels:
    app: password-recovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-recovery-service
  template:
    metadata:
      labels:
        app: password-recovery-service
    spec:
      containers:
        - name: password-recovery-service
          image: ismail039/password-recovery-service
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_APPLICATION_NAME
              value: "passwordrecovery-service"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://localhost:3306/passwordS?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              value: "ismailelmtioui2357@gmail.com"
            - name: SPRING_MAIL_PASSWORD
              value: "entrffnrzmnobxyd"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"
            - name: SERVER_PORT
              value: "8091"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://localhost:8761/eureka/"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "prometheus"
---
apiVersion: v1
kind: Service
metadata:
  name: password-recovery-service
spec:
  selector:
    app: password-recovery-service
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
